/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Announcement = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const GalleryItem = IDL.Record({
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'caption' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'isVeg' : IDL.Bool,
  'price' : IDL.Float64,
});
export const AppLogin = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'deviceInfo' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Time = IDL.Int;
export const Offer = IDL.Record({
  'title' : IDL.Text,
  'discountText' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'promoCode' : IDL.Text,
  'validUntil' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Dish = IDL.Record({
  'veg' : IDL.Bool,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const MenuCategory = IDL.Record({
  'name' : IDL.Text,
  'items' : IDL.Vec(Dish),
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'ready' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'dishName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'customerPhone' : IDL.Text,
  'cart' : IDL.Vec(OrderItem),
  'orderId' : IDL.Text,
  'specialInstructions' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'timestamp' : Time,
});
export const Testimonial = IDL.Record({
  'customerName' : IDL.Text,
  'review' : IDL.Text,
  'isApproved' : IDL.Bool,
  'dishName' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const RestaurantInfo = IDL.Record({
  'about' : IDL.Text,
  'storeHours' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const OrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'cart' : IDL.Vec(OrderItem),
  'specialInstructions' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAnnouncement' : IDL.Func([Announcement], [], []),
  'addGalleryItem' : IDL.Func([GalleryItem], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [], []),
  'addOffer' : IDL.Func([Offer], [], []),
  'approveTestimonial' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllAppLogins' : IDL.Func([], [IDL.Vec(AppLogin)], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(MenuItem)))],
      ['query'],
    ),
  'getOrderById' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([OrderInput], [IDL.Text], []),
  'removeAnnouncement' : IDL.Func([IDL.Text], [], []),
  'removeGalleryItem' : IDL.Func([IDL.Text], [], []),
  'removeMenuItem' : IDL.Func([IDL.Text], [], []),
  'removeOffer' : IDL.Func([IDL.Text], [], []),
  'removeTestimonial' : IDL.Func([IDL.Text], [], []),
  'saveAppLogin' : IDL.Func([AppLogin], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func([ContactMessage], [], []),
  'submitTestimonial' : IDL.Func([Testimonial], [], []),
  'updateAnnouncement' : IDL.Func([IDL.Text, Announcement], [], []),
  'updateGalleryItem' : IDL.Func([IDL.Text, GalleryItem], [], []),
  'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
  'updateOffer' : IDL.Func([IDL.Text, Offer], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateRestaurantInfo' : IDL.Func([RestaurantInfo], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Announcement = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const GalleryItem = IDL.Record({
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'caption' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'isVeg' : IDL.Bool,
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Offer = IDL.Record({
    'title' : IDL.Text,
    'discountText' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'promoCode' : IDL.Text,
    'validUntil' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Dish = IDL.Record({
    'veg' : IDL.Bool,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const MenuCategory = IDL.Record({
    'name' : IDL.Text,
    'items' : IDL.Vec(Dish),
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'ready' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'dishName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'customerPhone' : IDL.Text,
    'cart' : IDL.Vec(OrderItem),
    'orderId' : IDL.Text,
    'specialInstructions' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'timestamp' : Time,
  });
  const Testimonial = IDL.Record({
    'customerName' : IDL.Text,
    'review' : IDL.Text,
    'isApproved' : IDL.Bool,
    'dishName' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const RestaurantInfo = IDL.Record({
    'about' : IDL.Text,
    'storeHours' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const OrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'cart' : IDL.Vec(OrderItem),
    'specialInstructions' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAnnouncement' : IDL.Func([Announcement], [], []),
    'addGalleryItem' : IDL.Func([GalleryItem], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [], []),
    'addOffer' : IDL.Func([Offer], [], []),
    'approveTestimonial' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllAppLogins' : IDL.Func([], [IDL.Vec(AppLogin)], ['query']),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getAllContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'getAllGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(MenuItem)))],
        ['query'],
      ),
    'getOrderById' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Order)],
        ['query'],
      ),
    'getOrdersByPhone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([OrderInput], [IDL.Text], []),
    'removeAnnouncement' : IDL.Func([IDL.Text], [], []),
    'removeGalleryItem' : IDL.Func([IDL.Text], [], []),
    'removeMenuItem' : IDL.Func([IDL.Text], [], []),
    'removeOffer' : IDL.Func([IDL.Text], [], []),
    'removeTestimonial' : IDL.Func([IDL.Text], [], []),
    'saveAppLogin' : IDL.Func([AppLogin], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func([ContactMessage], [], []),
    'submitTestimonial' : IDL.Func([Testimonial], [], []),
    'updateAnnouncement' : IDL.Func([IDL.Text, Announcement], [], []),
    'updateGalleryItem' : IDL.Func([IDL.Text, GalleryItem], [], []),
    'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
    'updateOffer' : IDL.Func([IDL.Text, Offer], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateRestaurantInfo' : IDL.Func([RestaurantInfo], [], []),
  });
};

export const init = ({ IDL }) => { return []; };