/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'title' : string,
  'body' : string,
  'isActive' : boolean,
}
export interface ContactMessage {
  'name' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Dish {
  'veg' : boolean,
  'name' : string,
  'category' : string,
  'price' : number,
}
export interface GalleryItem {
  'isActive' : boolean,
  'imageUrl' : string,
  'caption' : string,
}
export interface MenuCategory { 'name' : string, 'items' : Array<Dish> }
export interface MenuItem {
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'isVeg' : boolean,
  'price' : number,
}
export interface Offer {
  'title' : string,
  'discountText' : string,
  'description' : string,
  'isActive' : boolean,
  'promoCode' : string,
  'validUntil' : Time,
}
export interface AppLogin {
  'name' : string,
  'phone' : string,
  'deviceInfo' : string,
  'timestamp' : Time,
}
export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'customerPhone' : string,
  'cart' : Array<OrderItem>,
  'orderId' : string,
  'specialInstructions' : string,
  'totalAmount' : number,
  'address' : string,
  'timestamp' : Time,
}
export interface OrderInput {
  'customerName' : string,
  'customerPhone' : string,
  'cart' : Array<OrderItem>,
  'specialInstructions' : string,
  'totalAmount' : number,
  'address' : string,
}
export interface OrderItem {
  'dishName' : string,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'preparing' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'ready' : null };
export interface RestaurantInfo {
  'about' : string,
  'storeHours' : string,
  'contactDetails' : string,
}
export interface Testimonial {
  'customerName' : string,
  'review' : string,
  'isApproved' : boolean,
  'dishName' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAnnouncement' : ActorMethod<[Announcement], undefined>,
  'addGalleryItem' : ActorMethod<[GalleryItem], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'addOffer' : ActorMethod<[Offer], undefined>,
  'approveTestimonial' : ActorMethod<[string, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[string, string], undefined>,
  'getAllAppLogins' : ActorMethod<[], Array<AppLogin>>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllCategories' : ActorMethod<[], Array<MenuCategory>>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOffers' : ActorMethod<[], Array<Offer>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuByCategory' : ActorMethod<[], Array<[string, Array<MenuItem>]>>,
  'getOrderById' : ActorMethod<[string, string], [] | [Order]>,
  'getOrdersByPhone' : ActorMethod<[string], Array<Order>>,
  'getRestaurantInfo' : ActorMethod<[], RestaurantInfo>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[OrderInput], string>,
  'removeAnnouncement' : ActorMethod<[string], undefined>,
  'removeGalleryItem' : ActorMethod<[string], undefined>,
  'removeMenuItem' : ActorMethod<[string], undefined>,
  'removeOffer' : ActorMethod<[string], undefined>,
  'removeTestimonial' : ActorMethod<[string], undefined>,
  'saveAppLogin' : ActorMethod<[AppLogin], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'submitTestimonial' : ActorMethod<[Testimonial], undefined>,
  'updateAnnouncement' : ActorMethod<[string, Announcement], undefined>,
  'updateGalleryItem' : ActorMethod<[string, GalleryItem], undefined>,
  'updateMenuItem' : ActorMethod<[string, MenuItem], undefined>,
  'updateOffer' : ActorMethod<[string, Offer], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateRestaurantInfo' : ActorMethod<[RestaurantInfo], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];